/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/ 

module derelict.purple.sound_theme;

import derelict.glib.gtypes;
import derelict.glib.glibconfig;
import derelict.purple.theme;

extern (C):

alias _PurpleSoundTheme PurpleSoundTheme;
alias _PurpleSoundThemeClass PurpleSoundThemeClass;

struct _PurpleSoundTheme
{
	PurpleTheme parent;
	gpointer priv;
}

struct _PurpleSoundThemeClass
{
	PurpleThemeClass parent_class;
}


extern( C ) nothrow 
{
    alias da_purple_sound_theme_get_type = GType function();																		
    alias da_purple_sound_theme_get_file = const(gchar)* function(PurpleSoundTheme* theme, const(gchar)* event);					
    alias da_purple_sound_theme_get_file_full = gchar* function(PurpleSoundTheme* theme, const(gchar)* event);						
    alias da_purple_sound_theme_set_file = void function(PurpleSoundTheme* theme, const(gchar)* event, const(gchar)* filename);		
}

__gshared
{
	da_purple_sound_theme_get_type purple_sound_theme_get_type;
	da_purple_sound_theme_get_file purple_sound_theme_get_file;
	da_purple_sound_theme_get_file_full purple_sound_theme_get_file_full;
	da_purple_sound_theme_set_file purple_sound_theme_set_file;
}