/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/ 

module derelict.glib.ggettext;

import derelict.glib.gtypes;
import derelict.glib.glibconfig;
import core.stdc.config;

extern (C):

extern( C ) nothrow 
{
    alias da_g_strip_context = const(gchar)* function(const(gchar)* msgid, const(gchar)* msgval);										
    alias da_g_dgettext = const(gchar)* function(const(gchar)* domain, const(gchar)* msgid);											
    alias da_g_dcgettext = const(gchar)* function(const(gchar)* domain, const(gchar)* msgid, gint category);							
    alias da_g_dngettext = const(gchar)* function(const(gchar)* domain, const(gchar)* msgid, const(gchar)* msgid_plural, gulong n);		
    alias da_g_dpgettext = const(gchar)* function(const(gchar)* domain, const(gchar)* msgctxtid, gsize msgidoffset);					
    alias da_g_dpgettext2 = const(gchar)* function(const(gchar)* domain, const(gchar)* context, const(gchar)* msgid);					
}

__gshared
{
    da_g_strip_context g_strip_context; 
    da_g_dgettext g_dgettext; 
    da_g_dcgettext g_dcgettext; 
    da_g_dngettext g_dngettext; 
    da_g_dpgettext g_dpgettext; 
    da_g_dpgettext2 g_dpgettext2; 
}