/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/ 

module derelict.purple.enum_types;

import derelict.glib.gtypes;
import derelict.glib.glibconfig;

extern (C):

alias _Anonymous_0 PurpleMediaCandidateType;
alias _Anonymous_1 PurpleMediaCaps;
alias _Anonymous_2 PurpleMediaComponentType;
alias _Anonymous_3 PurpleMediaInfoType;
alias _Anonymous_4 PurpleMediaNetworkProtocol;
alias _Anonymous_5 PurpleMediaSessionType;
alias _Anonymous_6 PurpleMediaState;

enum _Anonymous_0
{
	PURPLE_MEDIA_CANDIDATE_TYPE_HOST = 0,
	PURPLE_MEDIA_CANDIDATE_TYPE_SRFLX = 1,
	PURPLE_MEDIA_CANDIDATE_TYPE_PRFLX = 2,
	PURPLE_MEDIA_CANDIDATE_TYPE_RELAY = 3,
	PURPLE_MEDIA_CANDIDATE_TYPE_MULTICAST = 4
}

enum _Anonymous_1
{
	PURPLE_MEDIA_CAPS_NONE = 0,
	PURPLE_MEDIA_CAPS_AUDIO = 1,
	PURPLE_MEDIA_CAPS_AUDIO_SINGLE_DIRECTION = 2,
	PURPLE_MEDIA_CAPS_VIDEO = 4,
	PURPLE_MEDIA_CAPS_VIDEO_SINGLE_DIRECTION = 8,
	PURPLE_MEDIA_CAPS_AUDIO_VIDEO = 16,
	PURPLE_MEDIA_CAPS_MODIFY_SESSION = 32,
	PURPLE_MEDIA_CAPS_CHANGE_DIRECTION = 64
}

enum _Anonymous_2
{
	PURPLE_MEDIA_COMPONENT_NONE = 0,
	PURPLE_MEDIA_COMPONENT_RTP = 1,
	PURPLE_MEDIA_COMPONENT_RTCP = 2
}

enum _Anonymous_3
{
	PURPLE_MEDIA_INFO_HANGUP = 0,
	PURPLE_MEDIA_INFO_ACCEPT = 1,
	PURPLE_MEDIA_INFO_REJECT = 2,
	PURPLE_MEDIA_INFO_MUTE = 3,
	PURPLE_MEDIA_INFO_UNMUTE = 4,
	PURPLE_MEDIA_INFO_PAUSE = 5,
	PURPLE_MEDIA_INFO_UNPAUSE = 6,
	PURPLE_MEDIA_INFO_HOLD = 7,
	PURPLE_MEDIA_INFO_UNHOLD = 8
}

enum _Anonymous_4
{
	PURPLE_MEDIA_NETWORK_PROTOCOL_UDP = 0,
	PURPLE_MEDIA_NETWORK_PROTOCOL_TCP = 1
}

enum _Anonymous_5
{
	PURPLE_MEDIA_NONE = 0,
	PURPLE_MEDIA_RECV_AUDIO = 1,
	PURPLE_MEDIA_SEND_AUDIO = 2,
	PURPLE_MEDIA_RECV_VIDEO = 4,
	PURPLE_MEDIA_SEND_VIDEO = 8,
	PURPLE_MEDIA_AUDIO = 3,
	PURPLE_MEDIA_VIDEO = 12
}

enum _Anonymous_6
{
	PURPLE_MEDIA_STATE_NEW = 0,
	PURPLE_MEDIA_STATE_CONNECTED = 1,
	PURPLE_MEDIA_STATE_END = 2
}


alias da_purple_media_candidate_type_get_type = GType function();																																																						/* da_purple_media_candidate_type_get_type purple_media_candidate_type_get_type; */
alias da_purple_media_caps_get_type = GType function();																																																						/* da_purple_media_caps_get_type purple_media_caps_get_type; */
alias da_purple_media_info_type_get_type = GType function();																																																						/* da_purple_media_info_type_get_type purple_media_info_type_get_type; */
alias da_purple_media_network_protocol_get_type = GType function();																																																						/* da_purple_media_network_protocol_get_type purple_media_network_protocol_get_type; */
alias da_purple_media_session_type_get_type = GType function();																																																						/* da_purple_media_session_type_get_type purple_media_session_type_get_type; */
alias da_purple_media_state_changed_get_type = GType function();																																																						/* da_purple_media_state_changed_get_type purple_media_state_changed_get_type; */



extern( C ) nothrow 
{
	
}

__gshared
{
	
}