/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/ 

module derelict.purple.nat_pmp;

import derelict.glib.gtypes;
import derelict.glib.glibconfig;

extern (C):

alias _Anonymous_0 PurplePmpType;

enum _Anonymous_0
{
	PURPLE_PMP_TYPE_UDP = 0,
	PURPLE_PMP_TYPE_TCP = 1
}

alias da_purple_pmp_init = void function();																																																						/* da_purple_pmp_init purple_pmp_init; */
alias da_purple_pmp_get_public_ip = char* function();																																																						/* da_purple_pmp_get_public_ip purple_pmp_get_public_ip; */
alias da_purple_pmp_create_map = gboolean function(PurplePmpType type, ushort privateport, ushort publicport, int lifetime);																																																						/* da_purple_pmp_create_map purple_pmp_create_map; */
alias da_purple_pmp_destroy_map = gboolean function(PurplePmpType type, ushort privateport);																																																						/* da_purple_pmp_destroy_map purple_pmp_destroy_map; */


extern( C ) nothrow 
{
	
}

__gshared
{
	
}