/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/ 

module derelict.purple.theme_loader;

import derelict.glib.gtypes;
import derelict.glib.glibconfig;
import derelict.purple.theme;

extern (C):

alias _PurpleThemeLoader PurpleThemeLoader;
alias _PurpleThemeLoaderClass PurpleThemeLoaderClass;

struct _PurpleThemeLoader
{
	GObject parent;
	gpointer priv;
}

struct _PurpleThemeLoaderClass
{
	GObjectClass parent_class;
	//<unimplemented> function (const(gchar)*) purple_theme_loader_build;
}

alias da_purple_theme_loader_get_type = GType function();																																																						/* da_purple_theme_loader_get_type purple_theme_loader_get_type; */
alias da_purple_theme_loader_get_type_string = const(gchar)* function(PurpleThemeLoader* self);																																																						/* da_purple_theme_loader_get_type_string purple_theme_loader_get_type_string; */
alias da_purple_theme_loader_build = PurpleTheme* function(PurpleThemeLoader* loader, const(gchar)* dir);																																																						/* da_purple_theme_loader_build purple_theme_loader_build; */


extern( C ) nothrow 
{
	
}

__gshared
{
	
}